### ISSUE TITLE
syntax error linking player-details.jsp

### ISSUE THREAD

**Issue by MapiTenas** [AlejandroACG/roleplaying-web-app#4]
Please add a final "s" in player details button:

a href="player-detail.jsp" class="btn btn-primary rounded-pill px-3">Details</a
this should be:

a href="player-**details**.jsp" class="btn btn-primary rounded-pill px-3">Details</a

Thank you!

**Comment by RubenLCgit** [comment]
Bug fixed

f58a1530bc0d10800d38ec56610861e77b6ae2ee
